strings:
  ru:
    main_menu:
      title: "Главное меню"
      options:
        - label: "Список мероприятий"
          value: "events"
        - label: "Обратная связь"
          value: "contact"
  en:
    main_menu:
      title: "Main menu"
      options:
        - label: "Events list"
          value: "events"
        - label: "Contact"
          value: "contact"
