name: "telegram_bot"
version: "1.2.0"
lang: "en"
timezone: "Europe/Paris"
antiflood:
  enabled: true
  time_window_seconds: 2
strings:
  en:
    cancel: "Cancel"
    operation_cancelled: "Operation cancelled."
  ru:
    cancel: "Отмена"
    operation_cancelled: "Операция отменена."