app:
  name: "events_bot"
  version: "0.1.0"
  lang: "ru"
  timezone: "Europe/Paris"
  antiflood:
    enabled: true
    time_window_seconds: 2
strings:
  en:
    cancel: "Cancel"
    operation_cancelled: "Operation cancelled."
  ru:
    cancel: "Отмена"
    operation_cancelled: "Операция отменена."