strings:
  ru:
    no_rights: "У вас нет прав администратора для доступа к этому приложению"
    menu:
      title: "Меню администратора"
      options:
        - label: "Экспорт данных"
          value: "export_data"
        - label: "Публичное сообщение"
          value: "public_message"
        - label: "Управление пользователями"
          value: "users"
        - label: "Создать мероприятие"
          value: "create_event"
        - label: "Удалить мероприятие"
          value: "delete_event"
        - label: "О приложении"
          value: "about"
    create_event:
      title_prompt: "Введите название мероприятия:"
      description_prompt: "Введите описание мероприятия:"
      qtickets_prompt: "Введите ссылку на билеты (или отправьте 'skip' чтобы пропустить):"
      datetime_prompt: "Введите дату и время мероприятия (YYYY-MM-DD HH:MM) или 'skip':"
      image_prompt: "Отправьте изображение для мероприятия или отправьте 'skip':"
      success: "Мероприятие '{name}' успешно создано!"
      error: "Ошибка при создании мероприятия: {error}"
      cancel: "Создание мероприятия отменено"
      invalid_datetime: "Неверный формат даты. Используйте YYYY-MM-DD HH:MM"
    cancel: "Отмена"
  en:
    no_rights: "You do not have admin rights to access this application"
    menu:
      title: "Admin menu"
      options:
        - label: "Export data"
          value: "export_data"
        - label: "Public message"
          value: "public_message"
        - label: "User management"
          value: "users"
        - label: "Create Event"
          value: "create_event"
        - label: "About"
          value: "about"
    create_event:
      title_prompt: "Enter event title:"
      description_prompt: "Enter event description:"
      qtickets_prompt: "Enter tickets link (or send 'skip' to skip):"
      datetime_prompt: "Enter event date and time (YYYY-MM-DD HH:MM) or 'skip':"
      image_prompt: "Send event image or send 'skip':"
      success: "Event '{name}' created successfully!"
      error: "Error creating event: {error}"
      cancel: "Event creation cancelled"
      invalid_datetime: "Invalid date format. Use YYYY-MM-DD HH:MM"
    cancel: "Cancel"
